webtalk_init -webtalk_dir C:/Users/alois/OneDrive/Documents/Perso/M2_SE/VHDL/SPI/SPI/SPI.sim/sim_1/behav/xsim/xsim.dir/SPI_Master_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 25 12:56:37 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4bb90980-2ffe-478f-9965-7c390f62c0d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e9bd8dbed53f4cae84ee8f01d114bd2d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "82" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3920680829 -regid "" -xml C:/Users/alois/OneDrive/Documents/Perso/M2_SE/VHDL/SPI/SPI/SPI.sim/sim_1/behav/xsim/xsim.dir/SPI_Master_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/alois/OneDrive/Documents/Perso/M2_SE/VHDL/SPI/SPI/SPI.sim/sim_1/behav/xsim/xsim.dir/SPI_Master_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/alois/OneDrive/Documents/Perso/M2_SE/VHDL/SPI/SPI/SPI.sim/sim_1/behav/xsim/xsim.dir/SPI_Master_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
