# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/alois/Downloads/zedboard_master_XDC_RevC_D_v3.xdc

# Block Designs: bd/SPI/SPI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI || ORIG_REF_NAME==SPI} -quiet] -quiet

# IP: bd/SPI/ip/SPI_SPI_Master_0_0/SPI_SPI_Master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_SPI_Master_0_0 || ORIG_REF_NAME==SPI_SPI_Master_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_clk_wiz_0_0/SPI_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_clk_wiz_0_0 || ORIG_REF_NAME==SPI_clk_wiz_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_N_Divider_0_0/SPI_N_Divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_N_Divider_0_0 || ORIG_REF_NAME==SPI_N_Divider_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_Comparateur_0_0/SPI_Comparateur_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_Comparateur_0_0 || ORIG_REF_NAME==SPI_Comparateur_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_Compteur_8bits_0_0/SPI_Compteur_8bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_Compteur_8bits_0_0 || ORIG_REF_NAME==SPI_Compteur_8bits_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_xlconstant_0_0/SPI_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_xlconstant_0_0 || ORIG_REF_NAME==SPI_xlconstant_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_xlconcat_0_0/SPI_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_xlconcat_0_0 || ORIG_REF_NAME==SPI_xlconcat_0_0} -quiet] -quiet

# IP: bd/SPI/ip/SPI_xlconstant_1_0/SPI_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SPI_xlconstant_1_0 || ORIG_REF_NAME==SPI_xlconstant_1_0} -quiet] -quiet

# XDC: bd/SPI/ip/SPI_SPI_Master_0_0/src/zedboard_master_XDC_RevC_D_v3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SPI_SPI_Master_0_0 || ORIG_REF_NAME==SPI_SPI_Master_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/SPI/ip/SPI_clk_wiz_0_0/SPI_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SPI_clk_wiz_0_0 || ORIG_REF_NAME==SPI_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SPI/ip/SPI_clk_wiz_0_0/SPI_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SPI_clk_wiz_0_0 || ORIG_REF_NAME==SPI_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/SPI/ip/SPI_clk_wiz_0_0/SPI_clk_wiz_0_0_ooc.xdc

# XDC: bd/SPI/SPI_ooc.xdc
