set_property IOSTANDARD LVCMOS33 [get_ports {S[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {E[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {E[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {E[2]}]


set_property PACKAGE_PIN F22 [get_ports {E[0]}]
set_property PACKAGE_PIN G22 [get_ports {E[1]}]
set_property PACKAGE_PIN H22 [get_ports {E[2]}]
set_property PACKAGE_PIN T22 [get_ports {S[0]}]
set_property PACKAGE_PIN T21 [get_ports {S[1]}]
set_property PACKAGE_PIN U22 [get_ports {S[2]}]
set_property PACKAGE_PIN U21 [get_ports {S[3]}]
set_property PACKAGE_PIN V22 [get_ports {S[4]}]
set_property PACKAGE_PIN W22 [get_ports {S[5]}]
set_property PACKAGE_PIN U19 [get_ports {S[6]}]
set_property PACKAGE_PIN U14 [get_ports {S[7]}]


