# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/alois/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-5116-POTATO-PC/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.cache/wt [current_project]
set_property parent.project_path C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.srcs/sources_1/new/Bascule.vhd
  C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.srcs/sources_1/new/Clock_Div.vhd
  C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.srcs/sources_1/new/Global.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.srcs/constrs_1/new/PinOut.xdc
set_property used_in_implementation false [get_files C:/Users/alois/Vivado_Project/Compteur_Bascule/Compteur_Bascule.srcs/constrs_1/new/PinOut.xdc]

read_xdc C:/Users/alois/Vivado_Project/zedboard_master_XDC_RevC_D_v3.xdc
set_property used_in_implementation false [get_files C:/Users/alois/Vivado_Project/zedboard_master_XDC_RevC_D_v3.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Global -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Global.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Global_utilization_synth.rpt -pb Global_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
